@InitSpool install_sys
DEFINE LIB_USER=lib
DEFINE APP_USER=app

@C_User &LIB_USER
@C_User &APP_USER

PROMPT Directory input_dir
CREATE OR REPLACE DIRECTORY input_dir AS 'C:\input'
/
GRANT ALL ON DIRECTORY input_dir TO PUBLIC
/
GRANT EXECUTE ON UTL_File TO PUBLIC
/
GRANT EXECUTE ON DBMS_Lock TO PUBLIC
/
@EndSpool